services:
  ros:
    build: .
    working_dir: /project-storm
    volumes:
      - ./:/project-storm
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
